### ISSUE TITLE
Server throw error when client deletes all data in text area

### ISSUE THREAD

**Issue by nghiant3223** [takedesign/realtime-editor#2]
I use your demo, when I delete all data in the text area by hitting Ctrl A + Delete, server throws an error 
```
realtime-editor-master\demo\node_modules\diff-match-patch\index.js:100
    throw new Error('Null input. (diff_main)');
    ^

Error: Null input. (diff_main)
    at diff_match_patch.diff_main (D:\GitHub\realtime-editor-master\demo\node_modules\diff-match-patch\index.js:100:11)
    at realtimeEditor.syncText (D:\GitHub\realtime-editor-master\demo\node_modules\realtime-editor\index.js:156:14)
    at Socket.<anonymous> (D:\GitHub\realtime-editor-master\demo\node_modules\realtime-editor\index.js:29:9)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at D:\GitHub\realtime-editor-master\demo\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

and client raises "Connection lost. please wait.."

**Comment by lyngbach** [comment]
Hello there!

This plugin hasn't really been maintained lately.
However I believe this problem is due to sometimes the browser don't target the line element with the cursor because the line somehow ended up completely empty (should always as minimum have a `<br>` tag for empty lines/linebreaks) and therefor sends `null` to the server which throws the error you are seeing.

Until (if at all) this plugin gets updated you can manually solve this problem by changing the following line of code in the realtime-editor.js file

change this at line 132:
```javascript
div.innerHTML = this.text[t].text;
```

to this:
```javascript
div.innerHTML = (this.text[t].text.length > 0 ? this.text[t].text : '<br>');
```

This should default an empty line on to a proper `<br>` tag and thus eliminate your problem.. hopefully.

**Comment by nghiant3223** [comment]
It works like a charm!
